metadata:
  name: Python構文集
  short_name: Python構文集
  description: データ分析とかML向けのメモ
  language: ja
  url: 'http://localhost'
  pathPrefix: /
  gaTrackingId: null
  favicon: /assets/favicon.png
  themeColor: '#9c2b6a'
header:
  enabled: true
  logo: /assets/logo.png
  links: []
sidebar:
  ignoreIndex: false
  forcedNavOrder: []
  expanded: []
  groups: 
    - order: 1
      path: "/10_python"
      title: "Python"
    - order: 2
      path: "/11_dataframe"
      title: "DataFrame"
    - order: 3
      path: "/20_preprocessing"
      title: "データ加工"
    - order: 4
      path: "/30_visualization"
      title: "可視化"
    - order: 5
      path: "/40_analyzing"
      title: "分析"
    - order: 6
      path: "/50_feature-engineering"
      title: "特徴量エンジニアリング"
    - order: 7
      path: "/60_machine-learning"
      title: "機械学習"
    - order: 8
      path: "/80_image"
      title: "画像データ"
    - order: 9
      path: "/90_nlp"
      title: "自然言語"
  links: []
  poweredBy: {}
  enabled: true
pwa:
  enabled: true
  manifest:
    icon: /assets/logo.png
    display: minimal-ui
    crossOrigin: anonymous
features:
  editOnRepo:
    editable: true
    location: 'https://github.com/yakipudding/data-analytics-python'
    type: github
  search:
    enabled: true,
    indexName: 'myindex'
    engine: 'algolia'
    excerptSize: 10000
    placeholder: 'Search here...'
    startComponent: 'input'
    debounceTime: 380,
    snippetLength: 22,
    hitsPerPage: 10,
    showStats: true,
    pagination:
      enabled: true,
      totalPages: 10,
      showNext: true,
      showPrevious: true
  rss:
    enabled: false
    showIcon: true
    copyright: ''
    categories: []
    matchRegex: ^/
    outputPath: /rss.xml
  darkMode:
    enabled: true
    default: false
social:
  github: 'https://github.com/yakipudding/data-analytics-python'
  twitter: 'https://twitter.com/yakipudding'
search:
  enabled: true
  startComponent: input
  placeholder: 検索...
  pagination:
    enabled: true
