# This is default jargon that you can use. Feel free to change it. See: https://boogi.netlify.app/editing/rich_content/abbreviations
'データ分析のためのPython構文集':
  name: データ分析のためのPython構文集
  long_name: データ分析のためのPython構文集
  description: データ分析に使えるPythonの構文を集めました
